### ISSUE TITLE
Infinite while loop in similarity search

### ISSUE THREAD

**Issue by MarkejN** [MetaModels/attribute_levenshtein#8]
## My environment is:

| Key                           | Value             | Comments   |
| ----------------------------- | ----------------- | ---------- |
| PHP version:                  | 8.2.9               |            |
| Contao version:               | 4.13.32           |            |
| MetaModels version:           | dev-feature/2.3.0 |            |
| Installation via composer     | yes               | `^2.3@dev` |
| Installed MetaModels packages | 26                |            |

## Issue description

The while loop in `src/Attribute/LevenshteinIndexLookup.php#processCandidates` executes `executeQuery()` again and again and thus only processes the first result of `fetchAssociative()` each time. The result of the query should (as far as I can see) be stored in a variable beforehand, otherwise this leads to an infinite loop for me.

## Steps to reproduce

1. Create a `levenshtein` attribute
2. Create a `levenshtein` filter
3. Search in the frontend with a misspelled word to use similarity search

## Describe the behaviour of the application

The application crashes at `max_execution_time` because the mentioned while loop never ends.

## Describe the expected behaviour of the application

The while loop should actually loop through the query results.

## Proposed Solution

```diff
@@ -501,7 +501,9 @@ class LevenshteinIndexLookup
      */
     private function processCandidates(ResultSet $resultSet, string $chunk, Statement $results, int $distance): void
     {
-        while ($result = $results->executeQuery()->fetchAssociative()) {
+        $queryResult = $results->executeQuery();
+
+        while ($result = $queryResult->fetchAssociative()) {
             if (empty($result['attribute']) || empty($result['item'])) {
                 continue;
             }
```

**Comment by zonky2** [comment]
Fixed in MM 2.3

**Comment by MarkejN** [comment]
Thank you for the quick response 👍 But I still get an error due to a missing use statement:

```diff
- use Doctrine\DBAL\Statement;
+ use Doctrine\DBAL\Result;
```

**Comment by zonky2** [comment]
fixed - pls wait ~ 5 minutes
